"use client";

import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Wand2, Loader2 } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import { generatePrompt, type PromptBrief } from "@/lib/api/prompt";
import type { PromptData } from "@/types/prompt";

interface AutoGenerateDialogProps {
  onGenerate: (data: PromptData) => void;
}

export function AutoGenerateDialog({ onGenerate }: AutoGenerateDialogProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);
  const { toast } = useToast();

  const [brief, setBrief] = useState<PromptBrief>({
    courseName: "",
    problem: "",
    audience: "",
    solution: "",
    currentMethod: ""
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      const data = await generatePrompt(brief);
      onGenerate(data);
      setIsOpen(false);
      toast({
        title: "Success",
        description: "Generated prompt content successfully",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate prompt content",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700">
          <Wand2 className="mr-2 h-4 w-4" />
          Auto Generate
        </Button>
      </DialogTrigger>
      <DialogContent className="bg-[#0A0A0A] border-purple-500/20 text-white">
        <DialogHeader>
          <DialogTitle>Auto Generate Prompt Content</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4 mt-4">
          <div>
            <Label>Course Name</Label>
            <Input
              required
              value={brief.courseName}
              onChange={(e) => setBrief(prev => ({ ...prev, courseName: e.target.value }))}
              className="bg-white/10 border-purple-500/30"
              placeholder="e.g., Agency Growth Blueprint"
            />
          </div>
          <div>
            <Label>Problem</Label>
            <Input
              required
              value={brief.problem}
              onChange={(e) => setBrief(prev => ({ ...prev, problem: e.target.value }))}
              className="bg-white/10 border-purple-500/30"
              placeholder="e.g., Struggling to scale agency"
            />
          </div>
          <div>
            <Label>Solution</Label>
            <Input
              required
              value={brief.solution}
              onChange={(e) => setBrief(prev => ({ ...prev, solution: e.target.value }))}
              className="bg-white/10 border-purple-500/30"
              placeholder="e.g., Proven scaling framework"
            />
          </div>
          <div>
            <Label>Current Method</Label>
            <Input
              required
              value={brief.currentMethod}
              onChange={(e) => setBrief(prev => ({ ...prev, currentMethod: e.target.value }))}
              className="bg-white/10 border-purple-500/30"
              placeholder="e.g., Trial and error"
            />
          </div>
          <div>
            <Label>Target Audience</Label>
            <Input
              required
              value={brief.audience}
              onChange={(e) => setBrief(prev => ({ ...prev, audience: e.target.value }))}
              className="bg-white/10 border-purple-500/30"
              placeholder="e.g., Agency Owners"
            />
          </div>
          <Button 
            type="submit"
            disabled={isLoading}
            className="w-full bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700"
          >
            {isLoading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              'Generate Content'
            )}
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  );
}