"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Wand2, Loader2 } from "lucide-react";
import type { PromptData } from "@/types/prompt";
import { useToast } from "@/components/ui/use-toast";

interface AutoGenerateDialogProps {
  onGenerate: (data: PromptData) => void;
}

export function AutoGenerateDialog({ onGenerate }: AutoGenerateDialogProps) {
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [brief, setBrief] = useState({
    niche: "",
    audience: "",
    mainTopic: "",
    description: ""
  });

  const handleSubmit = async () => {
    if (!brief.niche || !brief.audience || !brief.mainTopic) {
      toast({
        title: "Missing Fields",
        description: "Please fill in all required fields",
        variant: "destructive",
      });
      return;
    }
    
    setLoading(true);
    try {
      const response = await fetch('/api/generate-content', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(brief),
      });

      if (!response.ok) {
        throw new Error('Failed to generate content');
      }
      
      const data = await response.json();
      onGenerate(data);
      setOpen(false);
      toast({
        title: "Success",
        description: "Content generated successfully",
      });
    } catch (error) {
      console.error('Failed to auto-generate:', error);
      toast({
        title: "Generation Failed",
        description: error instanceof Error ? error.message : "Failed to generate content. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button 
          className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white"
        >
          <Wand2 className="mr-2 h-4 w-4" />
          Auto Generate Content
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px] bg-gray-950 border-purple-500/20 text-white">
        <DialogHeader>
          <DialogTitle className="text-xl font-semibold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
            Generate Course Content
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4 mt-4">
          <div>
            <Label>Niche/Industry</Label>
            <Input
              required
              value={brief.niche}
              onChange={(e) => setBrief({ ...brief, niche: e.target.value })}
              placeholder="e.g., Digital Marketing, Real Estate"
              className="bg-white/10 border-purple-500/30 text-white"
            />
          </div>
          <div>
            <Label>Target Audience</Label>
            <Input
              value={brief.audience}
              onChange={(e) => setBrief({ ...brief, audience: e.target.value })}
              placeholder="e.g., Small Business Owners, Freelancers"
              className="bg-white/10 border-purple-500/30"
            />
          </div>
          <div>
            <Label>Main Topic</Label>
            <Input
              value={brief.mainTopic}
              onChange={(e) => setBrief({ ...brief, mainTopic: e.target.value })}
              placeholder="e.g., Social Media Marketing, Lead Generation"
              className="bg-white/10 border-purple-500/30"
            />
          </div>
          <div>
            <Label>Brief Description</Label>
            <Textarea
              value={brief.description}
              onChange={(e) => setBrief({ ...brief, description: e.target.value })}
              placeholder="Describe what you want to teach or sell..."
              className="bg-white/10 border-purple-500/30 min-h-[100px]"
            />
          </div>
          <Button 
            onClick={handleSubmit} 
            className="w-full bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white"
            disabled={loading}
          >
            {loading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              "Generate"
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}