"use client";

import { AutoGenerateDialog } from "./AutoGenerateDialog";
import type { PromptData } from "@/types/prompt";

interface PromptHeaderProps {
  onGenerate: (data: PromptData) => void;
}

export function PromptHeader({ onGenerate }: PromptHeaderProps) {
  return (
    <div className="text-center">
      <div className="flex justify-center mb-6">
        <AutoGenerateDialog onGenerate={onGenerate} />
      </div>
      <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-blue-400">
        Sales System Prompt Builder
      </h1>
      <p className="mt-4 text-gray-300 max-w-2xl mx-auto">
        Fill in the fields below to generate prompts for your complete sales system including landing pages, 
        bridge pages, and thank you pages.
      </p>
    </div>
  );
}