"use client";

import { AutoGenerateDialog } from "./AutoGenerateDialog";
import type { AscensionEmailData } from "@/types/email-ascension";

interface EmailHeaderProps {
  onGenerate: (data: AscensionEmailData) => void;
}

export function EmailHeader({ onGenerate }: EmailHeaderProps) {
  return (
    <div className="text-center">
      <div className="flex justify-center mb-6">
        <AutoGenerateDialog onGenerate={onGenerate} />
      </div>
      <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-blue-400">
        High-Ticket Ascension Email Sequence
      </h1>
      <p className="mt-4 text-gray-300 max-w-2xl mx-auto">
        Create a powerful 14-day email sequence to convert your customers into high-ticket clients through webinars, workshops, or strategy calls.
      </p>
    </div>
  );
}